on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.22.x, 1.23.x, 1.24.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test
        shell: bash
        run: |
          for i in 1 2 3; do
            echo "Attempt $i of 3"
            go test -v -bench=. ./... && break || if [ $i -eq 3 ]; then exit 1; fi
          done

  test-qemu:
    strategy:
      matrix:
        go-version: [1.22.x, 1.23.x, 1.24.x]
        arch: [386, arm, riscv64]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test
        env:
          GOARCH: ${{ matrix.arch }}
        run: |
          for i in 1 2 3; do
            echo "Attempt $i of 3"
            go test -v -bench=. ./... && break || if [ $i -eq 3 ]; then exit 1; fi
          done
